mywebsite/fileuploadapp/urls.py
from django.conf.urls import url

#from fileuploadapp import views
from .views import *

app_name = 'fileuploadapp'

urlpatterns = [

    # fileuploadapp/
    url(r'^$', HomeView.as_view(), name='apphome'),
    # fileuploadapp/register
    url(r'^upload/$', FileUploadEntry.as_view(), name='fileupload'),

]

from django.shortcuts import reverse

mywebsite/mywebsite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static

#from ..fileuploadapp.views import HomeView

urlpatterns = [
    #path('admin/', admin.site.urls),
    url(r'admin/', admin.site.urls),
    url(r'^home/', include('fileuploadapp.urls')),
    #url(r'^$home/', HomeView.as_view())
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mywebsite/fileuploadapp/models.py
from django.db import models
from django_tables2 import tables

# Create your models here.
from django.urls import reverse


class FileUpload(models.Model):

    #the variable to take the inputs
    file = models.FileField()
    processed = models.BooleanField(default=False)

    # on submit click on the user entry page, it redirects to the url below.
    def get_absolute_url(self):
        return reverse('fileuploadapp:apphome')


class FileUploadTable(tables.Table):
    class Meta:
        model=FileUpload

class FileData(models.Model):
    sku = models.CharField(max_length=15)
    name = models.CharField(max_length=200)
    price = models.CharField(max_length=50)

mywebsite/fileuploadapp/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic
from django.views.generic import CreateView
from django.http import HttpResponseRedirect

from .models import FileUpload, FileUploadTable, FileData


class HomeView(generic.ListView):
    # name of the object to be used in the index.html
    context_object_name = 'file_list'
    template_name = 'fileuploadapp/home_page.html'

    def get_queryset(self):
        table = FileUploadTable(FileUpload.objects.all())
        return table


# view for the user entry page
class FileUploadEntry(CreateView):
    model = FileUpload
    fields = ['file']
    template_name = 'fileuploadapp/user_form.html'

    def process_file(self, obj):
        file_obj = obj.file
        records=list()
        lines = file_obj.readlines()
        for eachline in lines:
            line = eachline.strip()
            if line:
                linedata = eval(line)
                records.append(FileData(sku=linedata[0], name=linedata[1], price=linedata[2]))
        process=False
        if records:
            FileData.objects.bulk_create(records)
            process=True
        finstance = FileUpload.objects.get(file=file_obj)
        finstance.processed = process
        finstance.save()

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.save()
        self.process_file(instance)
        return HttpResponseRedirect("/home")

mywebsite/fileuploadapp/templates/fileuploadapp/form-template.html
{% for field in form %}
    <div class="form-group">
        <label style="font-size: 20px;color: white; " >{{ field.label_tag }}</label>
        <div class="input" >{{ field }}</div>
    </div>
{% endfor %}

mywebsite/fileuploadapp/templates/fileuploadapp/home_page.html

{% load querystring from django_tables2 %}
{% load trans blocktrans from i18n %}
{% load bootstrap3 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<html>
<head>
<title class="title" >

</title>
    <style>
        th, td { white-space: nowrap; }
    div.dataTables_wrapper {
        margin: 0 auto;
    }

    div.container {
        width: 80%;
    }
    </style>
</head>

<body >

<h1> File Upload Application </h1>

{% block table %}
    <table class="table table-compact table-bordered"{% if file_list.attrs %} {{ file_list.attrs.as_html }}{% endif %}  style="width:100%">
        {% block table.thead %}
            <thead>
            <tr>
                {% for column in file_list.columns %}
                    {% if column.orderable %}
                        <th {{ column.attrs.th.as_html }}>{{ column.header }}</th>
                    {% else %}
                        <th {{ column.attrs.th.as_html }}>{{ column.header }}</th>
                    {% endif %}
                {% endfor %}
            </tr>
            </thead>
        {% endblock table.thead %}
        {% block table.tbody %}
            <tbody>
            {% for row in file_list.page.object_list|default:file_list.rows %} {# support pagination #}
                {% block table.tbody.row %}
                    <tr class="{% cycle 'odd' 'even' %}">
                        {% for column, cell in row.items %}
                            <td {{ column.attrs.td.as_html }}>{{ cell }}</td>
                        {% endfor %}
                        <td>
                                <button   type="submit" class="btn btn-primary"> Archive</button>
                                <button   type="submit" class="btn btn-primary"> Delete</button>
                        </td>
                    </tr>
                {% endblock table.tbody.row %}
            {% empty %}
                {% if file_list.empty_text %}
                    {% block table.tbody.empty_text %}
                        <tr><td colspan="{{ file_list.columns|length }}">{{ table.empty_text }}</td></tr>
                    {% endblock table.tbody.empty_text %}
                {% endif %}
            {% endfor %}
            </tbody>
        {% endblock table.tbody %}
        {% block table.tfoot %}
            <tfoot></tfoot>
        {% endblock table.tfoot %}
    </table>
{% endblock table %}


     <form action="{% url 'fileuploadapp:fileupload'  %}" method="post" class="form">
            {% csrf_token %}

            {% buttons %}
                <button   type="submit" class="btn btn-primary">
                    Upload New File
                </button>
            {% endbuttons %}
        </form>
</body>
</html>

mywebsite/fileuploadapp/templates/fileuploadapp/user_form.html
{% load querystring from django_tables2 %}
{% load trans blocktrans from i18n %}
{% load bootstrap3 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<html>
<head>

</head>
<body >

<h1>Upload New File</h1>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'fileuploadapp/form-template.html' %}
            <button type="submit" class="btn btn-primary">Submit</button>

</form>

</body>


</html>